import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { MiniKitProvider } from "@worldcoin/minikit-js/minikit-provider";
import "./globals.css";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunito.variable} font-sans h-dvh antialiased`}>
      <body className="h-dvh w-full">
        <MiniKitProvider props={{ appId: process.env.NEXT_PUBLIC_APP_ID }}>
          {children}
        </MiniKitProvider>
      </body>
    </html>
  );
}
